# Generated by Django 4.1.1 on 2022-09-12 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0018_auto_20201015_2036"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assigne_Organization_To_Requirements",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=20, null=True)),
                ("email", models.EmailField(max_length=100, null=True)),
                ("admitDate", models.DateField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
                ("totalRequirement", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="MainInstitutionRequirements",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_created=True)),
                (
                    "CRITERESType",
                    models.CharField(
                        choices=[
                            {"STAFF", "I.STAFF"},
                            {"II.ORGANIZATIO", "ORGANIZATIO"},
                            (
                                "III. INFRASTRUCTURE",
                                (
                                    (
                                        "III.1. External environment",
                                        "III.1. External environment",
                                    ),
                                    ("III.2. Building", " III.2. Building"),
                                    (
                                        "III.3. Sufficient hygiene",
                                        " III.3. Sufficient hygiene",
                                    ),
                                    (
                                        "III.4. Acceptable Space and Bed Management",
                                        "III.4. Acceptable Space and Bed Management",
                                    ),
                                    (
                                        "III.4.1. Waiting room and reception",
                                        " III.4.1. Waiting room and reception",
                                    ),
                                    (
                                        "III.4.2. Triage room and taking vital signs",
                                        " III.4.2. Triage room and taking vital signs",
                                    ),
                                    (
                                        "III.4.3. Consultation room",
                                        " III.4.3. Consultation room",
                                    ),
                                    (
                                        "III.4.4. Laboratory room",
                                        " III.4.4. Laboratory room",
                                    ),
                                    (
                                        "III.4.5. Sterilization room",
                                        " III.4.5. Sterilization room",
                                    ),
                                    (
                                        "III.4.6. Minor surgery room",
                                        " III.4.6. Minor surgery room",
                                    ),
                                    ("III.4.7. Nursing room", " III.4.7. Nursing room"),
                                    (
                                        "III.4.8. Hospitalization: (1/3 of beds: multi-position)",
                                        "III.4.8. Hospitalization: (1/3 of beds: multi-position)",
                                    ),
                                ),
                            ),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "OrganizationCategory",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "hospital"),
                            ("CLINIQUE", "clinique"),
                            ("MEDICAL", "medical"),
                            ("CENTER", "center"),
                            ("DENTAL_CENTER", "dental_centr"),
                            ("RABORATORY", "raboratory"),
                            ("CARAES", "caraes"),
                            ("POLYCLINIC", "polyclinic"),
                            ("OPTIONAL", "optional"),
                            ("PHARMACY", "pharmacy"),
                        ],
                        max_length=100,
                    ),
                ),
                ("CRITERESName", models.CharField(max_length=100, null=True)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MohComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=500, null=True)),
                ("time", models.DateTimeField(auto_now_add=True, null=True)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_ordered", models.DateTimeField(auto_now_add=True)),
                ("complete", models.BooleanField(default=False)),
                ("transaction_id", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.order",
                    ),
                ),
                (
                    "requiements",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.maininstitutionrequirements",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startdate", models.DateField(auto_created=True, null=True)),
                (
                    "photo",
                    models.ImageField(max_length=70, upload_to="media/%Y/%m/%d/"),
                ),
                ("organizationName", models.CharField(max_length=100, null=True)),
                (
                    "organizationcategory",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "hospital"),
                            ("CLINIQUE", "clinique"),
                            ("MEDICAL", "medical"),
                            ("CENTER", "center"),
                            ("DENTAL_CENTER", "dental_centr"),
                            ("RABORATORY", "raboratory"),
                            ("CARAES", "caraes"),
                            ("POLYCLINIC", "polyclinic"),
                            ("OPTIONAL", "optional"),
                            ("PHARMACY", "pharmacy"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("readerName", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(max_length=100, null=True)),
                ("organization_discription", models.TextField()),
                ("assignedRequirementId", models.PositiveIntegerField(null=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationFeedBack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=500, null=True)),
                ("time", models.DateTimeField(auto_now_add=True, null=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "nameofOrganization",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizationfeedback",
                        to="hospital.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endDate", models.DateField(auto_created=True, null=True)),
                ("startDate", models.DateTimeField(auto_created=True)),
                ("year", models.CharField(max_length=10)),
                ("nameOfperiod", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(max_length=200, null=True)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Vice_MayorOfSocialAffairsOftheHeadPHF_MOH",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pic/DoctorProfilePic/"
                    ),
                ),
                ("address", models.CharField(max_length=40)),
                ("mobile", models.CharField(max_length=20, null=True)),
                (
                    "department",
                    models.CharField(default="Social Affairs", max_length=50),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.DeleteModel(
            name="PatientDischargeDetails",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.organization",
            ),
        ),
        migrations.AddField(
            model_name="mohcomment",
            name="nameofOrganization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mohfeedback",
                to="hospital.organization",
            ),
        ),
        migrations.AddField(
            model_name="assigne_organization_to_requirements",
            name="organizatonName",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization",
                to="hospital.organization",
            ),
        ),
        migrations.AddField(
            model_name="assigne_organization_to_requirements",
            name="period",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userselectedRequirements",
                to="hospital.period",
            ),
        ),
        migrations.AddField(
            model_name="assigne_organization_to_requirements",
            name="requirementselected",
            field=models.ManyToManyField(
                related_name="subscriptions", to="hospital.maininstitutionrequirements"
            ),
        ),
    ]
