# Generated by Django 4.1.1 on 2022-09-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0019_assigne_organization_to_requirements_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assigne_organization_to_requirements",
            name="totalRequirement",
        ),
    ]
