# Generated by Django 4.1.1 on 2022-09-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hospital",
            "0020_remove_assigne_organization_to_requirements_totalrequirement",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="assignedRequirementId",
        ),
        migrations.AddField(
            model_name="organization",
            name="mobile",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
