# Generated by Django 4.1.1 on 2022-09-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0021_remove_organization_assignedrequirementid_and_more")
    ]

    operations = [
        migrations.RemoveField(model_name="organization", name="user"),
        migrations.AlterField(
            model_name="maininstitutionrequirements",
            name="CRITERESType",
            field=models.CharField(
                choices=[
                    {"I.STAFF", "STAFF"},
                    {"ORGANIZATIO", "II.ORGANIZATIO"},
                    {"EQUIPMENTS", "Equipment"},
                    (
                        "III. INFRASTRUCTURE",
                        (
                            (
                                "III.1. External environment",
                                "III.1. External environment",
                            ),
                            ("III.2. Building", " III.2. Building"),
                            ("III.3. Sufficient hygiene", " III.3. Sufficient hygiene"),
                            (
                                "III.4. Acceptable Space and Bed Management",
                                "III.4. Acceptable Space and Bed Management",
                            ),
                            (
                                "III.4.1. Waiting room and reception",
                                " III.4.1. Waiting room and reception",
                            ),
                            (
                                "III.4.2. Triage room and taking vital signs",
                                " III.4.2. Triage room and taking vital signs",
                            ),
                            (
                                "III.4.3. Consultation room",
                                " III.4.3. Consultation room",
                            ),
                            ("III.4.4. Laboratory room", " III.4.4. Laboratory room"),
                            (
                                "III.4.5. Sterilization room",
                                " III.4.5. Sterilization room",
                            ),
                            (
                                "III.4.6. Minor surgery room",
                                " III.4.6. Minor surgery room",
                            ),
                            ("III.4.7. Nursing room", " III.4.7. Nursing room"),
                            (
                                "III.4.8. Hospitalization: (1/3 of beds: multi-position)",
                                "III.4.8. Hospitalization: (1/3 of beds: multi-position)",
                            ),
                        ),
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_discription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
